Added poetry, and pre-commit hooks
robotpy/cxxheaderparser pull request #52
Opened 2023-05-22 07:44 UTC by nrbnlulu

poetry -  should help you in the build process and pypi publishing.
pre-commit-hooks - catches many common developer mistakes and auto-formats. 

pre-commit catched many errors, If you would be interested in this PR i'll fix them and probably add some workflows for testing as wel.

Best regards.

2023-05-22 13:08 UTC, auscompgeek requested changes

2023-05-22 13:08 UTC, auscompgeek commented on pyproject.toml
> +[tool.poetry]
If the package metadata is being moved into pyproject.toml, it should use PEP 621, not any legacy formats.

2023-05-22 13:08 UTC, auscompgeek commented on pyproject.toml
> +select = ["ALL"]
Do not enable `ALL`. We are not a Django project, nor are we a data science project.

2023-05-22 13:19 UTC, closed without merging

2023-05-22 13:22 UTC, nrbnlulu commented on cxxheaderparser/parser.py
> +from .types import Variable
https://github.com/asottile/reorder-python-imports#why-this-style

2023-05-22 22:05 UTC, auscompgeek commented on cxxheaderparser/parser.py
> +from .types import Variable
I don't remember the last time we had merge conflicts in import statements in any RobotPy project.

2023-05-23 03:49 UTC, virtuald commented
I don't really like poetry, and those "improved" imports are not improved.

2023-05-23 03:52 UTC, virtuald commented
Also worth noting, the reason I haven't published on pypi yet is because I don't want to commit to the API yet until I've used this project on a real project, and I've been meaning to do so for.. 2 years now. Soon?